const fs = require('fs');
let code = fs.readFileSync('components/AdminDashboard.tsx', 'utf8');

// The user noted the app version/expire update logic is duplicated in the "GENERAL SETTINGS" area, because it already exists in the "Deploy/Update App" tab natively. Let's remove the duplicated block.

const regex1 = /                                  <div>\n                                      <label className="text-\[10px\] font-bold uppercase text-slate-500">Latest Version \(e\.g\. 1\.0\.1\)<\/label>\n                                      <input \n                                          type="text" \n                                          value=\{localSettings\.latestVersion \|\| ''\} \n                                          onChange=\{e => setLocalSettings\(\{\.\.\.localSettings, latestVersion: e\.target\.value\}\)\} \n                                          className="w-full p-2 border rounded-lg text-sm font-bold font-mono"\n                                          placeholder="1\.0\.1" \n                                      \/>\n                                  <\/div>\n                                  <div>\n                                      <label className="text-\[10px\] font-bold uppercase text-slate-500">Update Link \(APK\/PlayStore\)<\/label>\n                                      <input \n                                          type="text" \n                                          value=\{localSettings\.updateUrl \|\| ''\} \n                                          onChange=\{e => setLocalSettings\(\{\.\.\.localSettings, updateUrl: e\.target\.value\}\)\} \n                                          className="w-full p-2 border rounded-lg text-sm text-blue-600"\n                                          placeholder="https:\/\/\.\.\." \n                                      \/>\n                                  <\/div>\n                                  <div>\n                                      <label className="text-\[10px\] font-bold uppercase text-slate-500">Launch Date & Time \(Timer Target\)<\/label>\n                                      <input \n                                          type="datetime-local" \n                                          value=\{localSettings\.launchDate \|\| ''\} \n                                          onChange=\{e => setLocalSettings\(\{\.\.\.localSettings, launchDate: e\.target\.value\}\)\} \n                                          className="w-full p-2 border rounded-lg text-sm font-bold"\n                                      \/>\n                                      <p className="text-\[9px\] text-orange-600 mt-1">\n                                          When this time is reached, the update popup will appear\. 7 days later, old app locks\.\n                                      <\/p>\n                                  <\/div>/;

code = code.replace(regex1, '');

fs.writeFileSync('components/AdminDashboard.tsx', code);
